services:
  db:
    image: postgres:16
    container_name: saas_dashboard_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: saas_dashboard
    ports:
      - "5432:5432"
    volumes:
      - ./backend/src/db/init:/docker-entrypoint-initdb.d
